sudo: true
language: cpp
os:
- osx
compiler:
- gcc
cache:
  directories:
    - "$HOME/Library/Caches/Homebrew"
script:
- curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/macpython-download-cache-and-build-module-wheels.sh -O
- chmod u+x macpython-download-cache-and-build-module-wheels.sh
- export ITK_PACKAGE_VERSION=v4.13.0
- ./macpython-download-cache-and-build-module-wheels.sh 2.7 3.5 3.6 3.7
- tar -zcvf dist.tar.gz dist/
- curl --upload-file dist.tar.gz https://transfer.sh/dist.tar.gz
