version: "0.0.1.{build}"

install:
  
  - cd ..
  - git clone https://github.com/T4mmi/ITKBinaryThinning3D
  - cd ITKBinaryThinning3D
  - curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/windows-download-cache-and-build-module-wheels.ps1 -O
  - ps: .\windows-download-cache-and-build-module-wheels.ps1
  - cd ..\ITKThickness3D
  - python C:\P\IPP\scripts\windows_build_module_wheels.py

build: off

test: off

artifacts:

  # pushing entire folder as a zip archive
  - path: dist\*