version: 2
jobs:
  build-and-test:
    working_directory: /ITKThickness3D-build
    docker:
      - image: insighttoolkit/module-ci:latest
    steps:
      - checkout:
          path: /ITKThickness3D
      - run:
          name: Build Module Dependencies
          command: |
            cd /
            git clone https://github.com/T4mmi/ITKBinaryThinning3D
            mkdir ITKBinaryThinning3D-build
            cd ITKBinaryThinning3D-build
            cmake -GNinja -DITK_DIR=/ITK-build ../ITKBinaryThinning3D
            ninja
      - run:
          name: Fetch CTest driver script
          command: |
            curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITK/dashboard/itk_common.cmake -O
      - run:
          name: Configure CTest script
          command: |
            SHASNIP=$(echo $CIRCLE_SHA1 | cut -c1-7)
            cat > dashboard.cmake << EOF
            set(CTEST_SITE "CircleCI")
            set(CTEST_BUILD_NAME "External-ITKThickness3D-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}-${SHASNIP}")
            set(CTEST_BUILD_CONFIGURATION "MinSizeRel")
            set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
            set(CTEST_BUILD_FLAGS: "-j5")
            set(CTEST_SOURCE_DIRECTORY /ITKThickness3D)
            set(CTEST_BINARY_DIRECTORY /ITKThickness3D-build)
            set(dashboard_model Experimental)
            set(dashboard_no_clean 1)
            set(dashboard_cache "
            ITK_DIR:PATH=/ITK-build
            BUILD_TESTING:BOOL=ON
            ")
            include(\${CTEST_SCRIPT_DIRECTORY}/itk_common.cmake)
            EOF
      - run:
          name: Build and Test
          no_output_timeout: 1.0h
          command: |
            ctest -j 2 -VV -S dashboard.cmake
  package:
    working_directory: ~/ITKThickness3D
    machine: true
    steps:
      - checkout
      - run:
          name: Fetch build script
          command: |
            curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh -O
            chmod u+x dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - run:
          name: Build Module Dependencies
          command: |
            cd ~
            git clone https://github.com/T4mmi/ITKBinaryThinning3D
            cd ITKBinaryThinning3D
            cp ~/ITKThickness3D/dockcross-manylinux-download-cache-and-build-module-wheels.sh .
            ./dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - run:
          name: Build Python packages
          no_output_timeout: 1.0h
          command: |
            cd ~/ITKThickness3D
            mv ~/ITKBinaryThinning3D/ITKPythonPackage .
            mv ~/ITKBinaryThinning3D/tools .
            ./ITKPythonPackage/scripts/dockcross-manylinux-build-module-wheels.sh
      - store_artifacts:
          path: dist
          destination: dist

workflows:
    version: 2
    build-test-package:
      jobs:
        - build-and-test
        - package
