name: clang-format linter

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: InsightSoftwareConsortium/ITKClangFormatLinterAction@master
      with:
        itk-branch: master
